### ISSUE TITLE
Got invalid coin denomination: got abera, expected stake: invalid request when run make start

### ISSUE THREAD

**Issue by shihao92** [berachain/polaris#1461]
Hello, I was trying to run the BERA chain node, and i ran into this issue below:

```
4:05AM ERR Sanitizing invalid gasprice oracle price cap module=polaris-geth provided=0 updated=500000000000
4:05AM ERR Sanitizing invalid gasprice oracle ignore price module=polaris-geth provided=0 updated=2
4:05AM ERR development etherbase in use - please verify this is intentional address=0xAf15f95bed0D3913a29092Fd7837451Ce4de64D3 module=polaris-geth
4:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc000c37ca0, staking}" version=0
4:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc001a12f20, mint}" version=0
4:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc001a26fd0, crisis}" version=0
4:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc001a302b0, evidence}" version=0
4:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc001a30ea0, consensus}" version=0
4:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc001a31670, evm}" version=0
4:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc0019a9bd0, bank}" version=0
4:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc000c36920, acc}" version=0
4:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc001a12320, slashing}" version=0
4:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc001a139a0, distribution}" version=0
4:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc001a26490, gov}" version=0
4:05AM INF Upgrading IAVL storage for faster queries + execution on live state. This may take a while commit=436F6D6D697449447B5B5D3A307D module=server store_key="KVStoreKey{0xc001a27aa0, upgrade}" version=0
4:05AM INF loading last state module=polaris-geth
4:05AM INF starting node with ABCI CometBFT in-process module=server
4:05AM INF service start impl=multiAppConn module=proxy msg="Starting multiAppConn service"
4:05AM INF service start connection=query impl=localClient module=abci-client msg="Starting localClient service"
4:05AM INF service start connection=snapshot impl=localClient module=abci-client msg="Starting localClient service"
4:05AM INF service start connection=mempool impl=localClient module=abci-client msg="Starting localClient service"
4:05AM INF service start connection=consensus impl=localClient module=abci-client msg="Starting localClient service"
4:05AM INF service start impl=EventBus module=events msg="Starting EventBus service"
4:05AM INF service start impl=PubSub module=pubsub msg="Starting PubSub service"
4:05AM INF service start impl=IndexerService module=txindex msg="Starting IndexerService service"
4:05AM INF ABCI Handshake App Info hash=E3B0C44298FC1C149AFBF4C8996FB92427AE41E4649B934CA495991B7852B855 height=0 module=consensus protocol-version=0 software-version=0.1.6-alpha-9-gec7dffcc
4:05AM INF ABCI Replay Blocks appHeight=0 module=consensus stateHeight=0 storeHeight=0
4:05AM INF InitChain chainID=polaris-2061 initialHeight=1 module=server
4:05AM INF initializing blockchain state from genesis.json module=server
4:05AM INF asserting crisis invariants inv=1/11 module=x/crisis name=distribution/nonnegative-outstanding
4:05AM INF asserting crisis invariants inv=2/11 module=x/crisis name=distribution/can-withdraw
4:05AM INF asserting crisis invariants inv=3/11 module=x/crisis name=distribution/reference-count
4:05AM INF asserting crisis invariants inv=4/11 module=x/crisis name=distribution/module-account
4:05AM INF asserting crisis invariants inv=5/11 module=x/crisis name=bank/nonnegative-outstanding
4:05AM INF asserting crisis invariants inv=6/11 module=x/crisis name=bank/total-supply
4:05AM INF asserting crisis invariants inv=7/11 module=x/crisis name=staking/module-accounts
4:05AM INF asserting crisis invariants inv=8/11 module=x/crisis name=staking/nonnegative-power
4:05AM INF asserting crisis invariants inv=9/11 module=x/crisis name=staking/positive-delegation
4:05AM INF asserting crisis invariants inv=10/11 module=x/crisis name=staking/delegator-shares
4:05AM INF asserting crisis invariants inv=11/11 module=x/crisis name=gov/module-account
4:05AM INF asserted all invariants duration=0.968013 height=0 module=x/crisis
```

then i got error
```
panic: failed to execute DeliverTx for '{
          "body": {
            "messages": [
              {
                "@type": "/cosmos.staking.v1beta1.MsgCreateValidator",
                "description": {
                  "moniker": "localtestnet",
                  "identity": "",
                  "website": "",
                  "security_contact": "",
                  "details": ""
                },
                "commission": {
                  "rate": "0.100000000000000000",
                  "max_rate": "0.200000000000000000",
                  "max_change_rate": "0.010000000000000000"
                },
                "min_self_delegation": "1",
                "delegator_address": "",
                "validator_address": "cosmosvaloper1ga7ttwq4s5w5kharj7zkzqjsufgw7q567l4xkj",
                "pubkey": {
                  "@type": "/cosmos.crypto.ed25519.PubKey",
                  "key": "e+GL6m9bEWEnTePQMh5Oc+eusgwhG/nR8cvas122nHA="
                },
                "value": {
                  "denom": "abera",
                  "amount": "1000000000000000000000"
                }
              }
            ],
            "memo": "e54053782a26d6f7dcb181fa662bbb2ef5b94bfa@83.229.84.79:26656",
            "timeout_height": "0",
            "extension_options": [],
            "non_critical_extension_options": []
          },
          "auth_info": {
            "signer_infos": [
              {
                "public_key": {
                  "@type": "/polaris.crypto.ethsecp256k1.v1.PubKey",
                  "key": "AqJQHrXktV3kw3yasrllDNWmzCJCQ4T4FeKaXlk1chV/"
                },
                "mode_info": {
                  "single": {
                    "mode": "SIGN_MODE_DIRECT"
                  }
                },
                "sequence": "0"
              }
            ],
            "fee": {
              "amount": [],
              "gas_limit": "200000",
              "payer": "",
              "granter": ""
            },
            "tip": null
          },
          "signatures": [
            "RdVUjGvR+jkpuLUFtECcnPE/kblYMP7FCKUoPPaXophYEtOnGXrD0AyesjQBjHdF7+WUpa5s1oilF60Ujre3xAE="
          ]
        }': failed to execute message; message index: 0: invalid coin denomination: got abera, expected stake: invalid request

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/genutil.AppModule.InitGenesis({{_}, {_, _}, {_, _}, {_, _}, {_, _}}, {{0x41883b0, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/x/genutil/module.go:108 +0x165
github.com/cosmos/cosmos-sdk/types/module.(*Manager).InitGenesis(_, {{0x41883b0, 0x606a400}, {0x41a5520, 0xc00219f380}, {{0x0, 0x0}, {0xc0012936e0, 0xc}, 0x0, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/types/module/module.go:508 +0x559
github.com/cosmos/cosmos-sdk/runtime.(*App).InitChainer(_, {{0x41883b0, 0x606a400}, {0x41a5520, 0xc00219f380}, {{0x0, 0x0}, {0xc0012936e0, 0xc}, 0x0, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/runtime/app.go:188 +0xf7
github.com/cosmos/cosmos-sdk/baseapp.(*BaseApp).InitChain(0xc00180efc0, 0xc000cce380)
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/baseapp/abci.go:105 +0x6a2
github.com/cosmos/cosmos-sdk/server.cometABCIWrapper.InitChain(...)
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/cmt_abci.go:32
github.com/cometbft/cometbft/abci/client.(*localClient).InitChain(0xc0008cc7e0?, {0x4188948?, 0x606a400?}, 0x70?)
	github.com/cometbft/cometbft@v0.38.5/abci/client/local_client.go:120 +0xd0
github.com/cometbft/cometbft/proxy.(*appConnConsensus).InitChain(0xc000cea6c0, {0x4188948, 0x606a400}, 0xc0012b0fc0?)
	github.com/cometbft/cometbft@v0.38.5/proxy/app_conn.go:78 +0x16d
github.com/cometbft/cometbft/consensus.(*Handshaker).ReplayBlocksWithContext(_, {_, _}, {{{0xb, 0x0}, {0x32d004c, 0x6}}, {0xc0012936e0, 0xc}, 0x1, ...}, ...)
	github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:336 +0xfec
github.com/cometbft/cometbft/consensus.(*Handshaker).HandshakeWithContext(0xc0016a93b0, {0x41888a0, 0xc000c47540}, {0x41a91b0?, 0xc000bf17a0?})
	github.com/cometbft/cometbft@v0.38.5/consensus/replay.go:274 +0x478
github.com/cometbft/cometbft/node.doHandshake({_, _}, {_, _}, {{{0xb, 0x0}, {0x32d004c, 0x6}}, {0xc0012936e0, 0xc}, ...}, ...)
	github.com/cometbft/cometbft@v0.38.5/node/setup.go:182 +0x1a9
github.com/cometbft/cometbft/node.NewNodeWithContext({0x41888a0, 0xc000c47540}, 0xc0000ee3c0, {0x416e7c0, 0xc001a0a0a0}, 0xc001fd0320, {0x4154c80, 0xc000f752c0}, 0x3c?, 0x3b9d568, ...)
	github.com/cometbft/cometbft@v0.38.5/node/node.go:350 +0x5b7
github.com/cosmos/cosmos-sdk/server.startCmtNode({0x41888a0, 0xc000c47540}, 0xc0000ee3c0, {0x41c7628?, 0xc0015b8600}, 0xc000cccf40)
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:402 +0x43f
github.com/cosmos/cosmos-sdk/server.startInProcess(_, {{{0x7fffeeabe64e, 0xb}, 0x0, {0x7fffeeabe5ea, 0x7}, {0x3339c1e, 0x1}, {0x3339c1e, 0x1}, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:348 +0x188
github.com/cosmos/cosmos-sdk/server.start(_, {{0x0, 0x0, 0x0}, {0x41ad870, 0xc0014a4090}, 0x0, {0x0, 0x0}, {0x41c7c28, ...}, ...}, ...)
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:266 +0x2f3
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2.1()
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:175 +0x5e
github.com/cosmos/cosmos-sdk/server.wrapCPUProfile(0xc000cccf40, 0xc00121f810)
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:600 +0x1b3
github.com/cosmos/cosmos-sdk/server.StartCmdWithOptions.func2(0xc000f44000?, {0xc00147edc0?, 0x1?, 0xa?})
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/start.go:174 +0x212
github.com/spf13/cobra.(*Command).execute(0xc000ef8000, {0xc00147ec80, 0xa, 0xa})
	github.com/spf13/cobra@v1.8.0/command.go:983 +0xabc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000bddb00)
	github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/spf13/cobra.(*Command).ExecuteContext(...)
	github.com/spf13/cobra@v1.8.0/command.go:1032
github.com/cosmos/cosmos-sdk/server/cmd.Execute(0xc00121ff30?, {0x0, 0x0}, {0xc0013789d0, 0xd})
	github.com/cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/server/cmd/execute.go:34 +0x187
main.main()
	github.com/berachain/polaris/e2e/testapp/polard/main.go:38 +0x38
make: *** [build/scripts/main.mk:158: start] Error 2
```
can someone pls help with this?

**Comment by shihao92** [comment]
after modified the abera to stake at genesis.json now im getting this
```
panic: failed to execute DeliverTx for '{"body":{"messages":[{"@type":"/cosmos.staking.v1beta1.MsgCreateValidator","description":{"moniker":"localtestnet","identity":"","website":"","security_contact":"","details":""},"commission":{"rate":"0.100000000000000000","max_rate":"0.200000000000000000","max_change_rate":"0.010000000000000000"},"min_self_delegation":"1","delegator_address":"","validator_address":"cosmosvaloper1ga7ttwq4s5w5kharj7zkzqjsufgw7q567l4xkj","pubkey":{"@type":"/cosmos.crypto.ed25519.PubKey","key":"e+GL6m9bEWEnTePQMh5Oc+eusgwhG/nR8cvas122nHA="},"value":{"denom":"abera","amount":"1000000000000000000000"}}],"memo":"e54053782a26d6f7dcb181fa662bbb2ef5b94bfa@83.229.84.79:26656","timeout_height":"0","extension_options":[],"non_critical_extension_options":[]},"auth_info":{"signer_infos":[{"public_key":{"@type":"/polaris.crypto.ethsecp256k1.v1.PubKey","key":"AqJQHrXktV3kw3yasrllDNWmzCJCQ4T4FeKaXlk1chV/"},"mode_info":{"single":{"mode":"SIGN_MODE_DIRECT"}},"sequence":"0"}],"fee":{"amount":[],"gas_limit":"200000","payer":"","granter":""},"tip":null},"signatures":["RdVUjGvR+jkpuLUFtECcnPE/kblYMP7FCKUoPPaXophYEtOnGXrD0AyesjQBjHdF7+WUpa5s1oilF60Ujre3xAE="]}': failed to execute message; message index: 0: invalid coin denomination: got abera, expected stake: invalid request
```

**Comment by aad3365** [comment]
me too getting this error on main branch ;(

**Comment by aad3365** [comment]
Hey I missed to install jq.
Do apt-get install jq and try again.

**Comment by shihao92** [comment]
wow amazing, works like a charm, thanks for helping in completing this last step to get the node works :))

**Comment by shihao92** [comment]
issues solved
